export default [
    {
        id: 11, 
        title: "Markdown Previewer",
        date: "29/04/2022",
        about: "Interactive markdown previewer. Solo project from the freeCodeCamp Front End Development Libraries Certificate.",
        pageUrl: "https://jethrosweb.github.io/2-markdown-previewer/",
        codeUrl: "https://github.com/jethrosweb/2-markdown-previewer",
        imageSrc: "./images/markdown-previewer.png",
        html: true, 
        css: false,
        scss: true,
        javascript: true,
        react: true
    },
    {
        id: 10, 
        title: "Quote Generator",
        date: "27/04/2022",
        about: "API driven interactive quote generator. Solo project from the freeCodeCamp Front End Development Libraries Certificate.",
        pageUrl: "https://jethrosweb.github.io/1-random-quote-machine/",
        codeUrl: "https://github.com/jethrosweb/1-random-quote-machine",
        imageSrc: "./images/quote-generator.png",
        html: true, 
        css: false,
        scss: true,
        javascript: true,
        react: true
    },
    {
        id: 9, 
        title: "Meme Generator",
        date: "06/04/2022",
        about: "API driven interactive meme generator. Project from the Scrimba/freeCodeCamp React tutorial series.",
        pageUrl: "https://jethrosweb.github.io/meme-generator/",
        codeUrl: "https://github.com/jethrosweb/meme-generator",
        imageSrc: "./images/meme-generator.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: true
    },
    {
        id: 8,
        title: "Travel Journal", 
        date: "01/04/2022", 
        about: "Local data driven internation travel journal. Solo project from the Scrimba/freeCodeCamp React tutorial series.",
        pageUrl: "https://jethrosweb.github.io/travel-journal/",
        codeUrl: "https://github.com/jethrosweb/travel-journal", 
        imageSrc: "./images/travel-journal.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: true
    },
    {
        id: 7,
        title: "Airbnb Clone",
        date: "30/03/2022",
        about: "Static Airbnb clone for mobile. Project from the Scrimba/freeCodeCamp React tutorial series.",
        pageUrl: "https://jethrosweb.github.io/airbnb-experiences-clone/",
        codeUrl: "https://github.com/jethrosweb/airbnb-experiences-clone", 
        imageSrc: "./images/airbnb-clone.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: true
    },
    {
        id: 6,
        title: "Calculator", 
        date: "25/03/2022", 
        about: "Vanilla Javascript calculator.", 
        pageUrl: "https://jethrosweb.github.io/calculator/",
        codeURL: "https://github.com/jethrosweb/calculator", 
        imageSrc: "./images/calculator.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: false
    },
    {
        id: 5,
        title: "Stopwatch", 
        date: "23/03/2022", 
        about: "Vanilla Javascript stopwatch.", 
        pageUrl: "https://jethrosweb.github.io/stopwatch/",
        codeUrl: "https://github.com/jethrosweb/stopwatch",
        imageSrc: "./images/stopwatch.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: false
    },
    {
        id: 4,
        title: "Digital Clock", 
        date: "23/03/2022", 
        about: "Vanilla Javascript digital clock.",
        pageUrl: "https://jethrosweb.github.io/digitialClock/",
        codeURL: "https://github.com/jethrosweb/digitialClock", 
        imageSrc: "./images/digital-clock.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: false
    },
    {
        id: 3,
        title: "Whac-A-Console",
        date: "22/03/2022", 
        about: "Vanilla Javascript coder version of Whac-A-Mole, Whac-A-Console. If you're feeling frustrated, whac-a-console the cost effective way.",
        pageUrl: "https://jethrosweb.github.io/whacAConsole/",
        codeUrl: "https://github.com/jethrosweb/whacAConsole",
        imageSrc: "./images/whac-a-console.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: false
    },
    {
        id: 2,
        title: "Invitation Designer",
        date: "10/03/2022", 
        about: "Interactive live wedding invitation designer. Optimal screen size (1200h X 1600w) for print. Part of the Academy Xi Web Development course.",
        pageUrl: "https://jethrosweb.github.io/weddingInvitationDesigner/",
        codeUrl: "https://github.com/jethrosweb/weddingInvitationDesigner",
        imageSrc: "./images/wedding-invitation.png",
        html: true, 
        css: true,
        scss: false,
        javascript: true,
        react: false
    },
    {
        id: 1,
        title: "Responsive Site", 
        date: "13/02/2022", 
        about: "My first responsive brochure site. Part of the Academy Xi Web Development course.",
        pageUrl: "http://salty-tin.surge.sh",
        codeUrl: "https://github.com/jethrosweb/responsive-brochure-site-lab",
        imageSrc: "./images/responsive-site.png",
        html: true, 
        css: true,
        scss: false,
        javascript: false,
        react: false
    }
]